### ISSUE TITLE
如果是通过Google账号登陆的，账密应该填写什么呢

### ISSUE THREAD

**Issue by pitaya-V** [Kengxxiao/Himari.ChatGPT#1]

**Comment by Kengxxiao** [comment]
目前暂时没有实现OAuth登录，可以临时使用账号和密码。
如果有需求的话后续会加上

**Comment by Kengxxiao** [comment]
已经支持以AccessToken形式登录。
按照新README提供的流程填写Google登录后获取的OAIAccessToken即可。

**Comment by pitaya-V** [comment]
感谢🙏

Kengxxiao ***@***.***> 于 2022年12月9日周五 20:13写道：
